services:
  app:
    container_name: laravel_app
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
#     depends_on:
#       - db

#   db:
#     image: postgres:16
#     container_name: postgres_db
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: ${DB_DATABASE}
#       POSTGRES_USER: ${DB_USERNAME}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
